### ISSUE TITLE
Snippets are missing

### ISSUE THREAD

**Issue by arossert** [harryzjm/Clipy#4]
Is this fork still maintained? 
It seems that the snippet option is missing on this one.

**Comment by arossert** [comment]
@harryzjm I see that you published a new version 3 weeks ago so it seems that this fork is still maintained, any idea why the snippet menu is missing?
<img width="123" alt="image" src="https://user-images.githubusercontent.com/7085494/233330528-f76ab70f-7b9e-401d-a7eb-3cd8e2ef6f7b.png">

**Comment by harryzjm** [comment]
I removed the snippet because of support theme and also I didn't use it, I choose SnippetsLab app. Additionally, I eliminated any functions related to network connectivity.

**Comment by arossert** [comment]
Hi, thanks for the response, I found the snippets feature very useful, since this is the best fork (and the only one that is working for me on M1), any chance you will consider adding them back 🙏

**Comment by petrovi4** [comment]
I also like this fork the most, but I can't switch to it because of the lack of snippets ((

**Comment by arossert** [comment]
@harryzjm Any chance you will consider adding back the snippets feature? Without it I cannot use this fork 🙏

**Comment by Bottacco** [comment]
Please @harryzjm add snippets again. I love Clipy but I can't live without its snippets. May be you could consider putting a checkmark in preferences to not show the snippets for those of you that don't use it?

**Comment by harryzjm** [comment]
OK, I'll put it on the agenda.

**Comment by Bottacco** [comment]
Great, thanks a lot!!!

**Comment by arossert** [comment]
This will be great to get the snippets back 💪🏻

**Comment by harryzjm** [comment]
Done @petrovi4 @Bottacco

**Comment by arossert** [comment]
Awesome, you are the best 💪🏻

**Comment by Bottacco** [comment]
> Done @petrovi4 @Bottacco

I am going to try it right away. Thanks a lot and cheers from Spain
