### ISSUE TITLE
Will not Launch on mac Mini M2 under 13.4.1 (c) 

### ISSUE THREAD

**Issue by RobBW** [harryzjm/Clipy#6]
FYI Launch fails with message:
/Applications/Utilities/Clipy.app/Contents/MacOS/Clipy ; exit;
Clipy/Realm+Migration.swift:61: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=1 "Provided schema version 7 is less than last set version 9." UserInfo={Error Name=InvalidSchemaVersion, NSLocalizedDescription=Provided schema version 7 is less than last set version 9., Error Code=1}
zsh: trace trap  /Applications/Utilities/Clipy.app/Contents/MacOS/Clipy

**Comment by harryzjm** [comment]
May be I think you should delete old realm db and reboot clipy will be ok, the path at `~/Library/Application Support/com.clipy-app.Clipy`

**Comment by RobBW** [comment]
Thank you. That worked perfectly
