### ISSUE TITLE
Clipy 1.4.0 not working on Sonoma

### ISSUE THREAD

**Issue by Bottacco** [harryzjm/Clipy#8]
I have just tried the latest version with snippets back and it is not working in several ways:

1) Whatever I copy to the clipboard doesn't appear in Clipy. I have restart it, I have deleted all traces of it and recreate prefs, etc… to no bail. I am running the latest Sonoma 14.0 version on an M2 Pro Mac mini.

2) I can open the Snippets window, create a folder, create a snippet, but no menu appears to choose the snippet like it did before inside the menu item (the original Clipy had an inline submenu in the menulet to show all folders and the snippets if you go into one of those folders). Only assigning a keyboard shortcut to the folder lets me choose the snippet or invoking the global Snippet shortcut (this behavior is expected).

3) I can't import my old snippets. I assume it is because the old exported file was an XML file and this new version generates JSON, so it must expect the same format to import it.

The first issue is the worst as it is not working at all.

Thanks a lot for this new Clipy version and I will be waiting for any solution to these issues.

**Comment by harryzjm** [comment]
1. Maybe I think you should check this path, 'System Settings' -> 'Privacy & Security' -> 'Accessibility', remove old Clipy, and add it.
2. I will check the original Clipy next time.
3. I changed to Json because it is supported natively by Apple.

**Comment by Bottacco** [comment]
The problem was that I have Sonoma. Now it works with version 1.4.1.

About the old XML export format, would it be to much work to include both, XML & JSON, on the import? Just use JSON for export, but many of us have a huge collection of snippets in the old Clipy that we need to transfer to your new version. If it complicates your version too much, any idea how to convert from XML to JSON directly before importing?

Thanks a lot for your effort and keeping alive this super useful utility. Cheers from Spain

**Comment by harryzjm** [comment]
I add a script used for translate
